version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: counter_db
    volumes:
      - ./data:/var/lib/mysql
      # import sql file to give permissions to user
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:  
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rassword
    ports:
<<<<<<< HEAD
      - "8080:8080"
=======
      - "8080:80"
>>>>>>> 2aca1a14cef403dd0b343cbfe728cb0d65ad67a7
    depends_on:
      - db
  nodejs:
    image: node:latest
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "3001:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=counter_db
    depends_on:
      - db
    command: npx nodemon ./server.js
