version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Halsnewram
      MYSQL_USER: tibthink
      MYSQL_PASSWORD: Halsnewram!18
    volumes:
      - ../data:/var/lib/mysql
    ports:
      - "3306:3306"

  nodejs:
    image: ./docker/DockerfileNodejs
    working_dir: /app
    volumes:
      - ../src:/app
    ports:
      - "80:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=tibthink
      - MYSQL_PASSWORD=Halsnewram!18
      - MYSQL_DATABASE=mydb
    depends_on:
      - db
      
    command: ["./wait-for-it.sh", "db:3306", "--", "npx", "nodemon", "./server.js"]


